/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyFoodSummary {
  'entries' : Array<FoodLogEntry>,
  'totals' : DailyTotals,
}
export interface DailyTotals {
  'calories' : number,
  'protein_g' : number,
  'carbs_g' : number,
  'fat_g' : number,
}
export type ExternalBlob = Uint8Array;
export interface FoodLogEntry {
  'date' : string,
  'calories' : number,
  'meal_type' : string,
  'protein_g' : number,
  'carbs_g' : number,
  'food_name' : string,
  'fat_g' : number,
}
export interface MacroTargets {
  'protein_g' : number,
  'carbs_g' : number,
  'fat_g' : number,
}
export interface MealTemplate {
  'allergy_tags' : Array<string>,
  'calories' : number,
  'name' : string,
  'description' : string,
  'protein_g' : number,
  'category' : string,
  'image' : ExternalBlob,
  'carbs_g' : number,
  'fat_g' : number,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'age' : bigint,
  'weight_kg' : number,
  'daily_calories' : bigint,
  'goal' : string,
  'name' : string,
  'macro_targets' : MacroTargets,
  'last_active' : Timestamp,
  'dietary_restrictions' : Array<string>,
  'height_cm' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightEntry { 'weight_kg' : number, 'date' : string }
export interface WorkoutExercise {
  'duration_seconds' : bigint,
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'animation_type' : string,
  'muscle_group' : string,
}
export interface WorkoutLog {
  'duration_minutes' : bigint,
  'date' : string,
  'workout_plan_id' : bigint,
  'completed' : boolean,
  'calories_burned' : number,
}
export interface WorkoutPlan {
  'duration_minutes' : bigint,
  'goal' : string,
  'difficulty' : string,
  'name' : string,
  'exercises' : Array<WorkoutExercise>,
  'description' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMealTemplate' : ActorMethod<[MealTemplate], bigint>,
  'addWorkoutPlan' : ActorMethod<[WorkoutPlan], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateBMI' : ActorMethod<[], number>,
  'chatWithNutritionAI' : ActorMethod<[string, string], string>,
  'deleteMealTemplate' : ActorMethod<[bigint], undefined>,
  'filterMealsByDietaryRestrictions' : ActorMethod<
    [Array<string>],
    Array<MealTemplate>
  >,
  'getAIMealSuggestions' : ActorMethod<
    [number, number, number, number],
    string
  >,
  'getAIWorkoutRecommendation' : ActorMethod<[string], string>,
  'getAllMealTemplates' : ActorMethod<[], Array<MealTemplate>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllWorkoutPlans' : ActorMethod<[], Array<WorkoutPlan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMealLogsByDate' : ActorMethod<[string], DailyFoodSummary>,
  'getMealTemplate' : ActorMethod<[bigint], MealTemplate>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightHistory' : ActorMethod<[], Array<WeightEntry>>,
  'getWorkoutPlan' : ActorMethod<[bigint], WorkoutPlan>,
  'getWorkoutsByDate' : ActorMethod<[string], Array<WorkoutLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logMeal' : ActorMethod<[FoodLogEntry], undefined>,
  'logWeight' : ActorMethod<[WeightEntry], undefined>,
  'logWorkout' : ActorMethod<[WorkoutLog], undefined>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMealTemplate' : ActorMethod<[bigint, MealTemplate], undefined>,
  'updateUser' : ActorMethod<[UserProfile], undefined>,
  'updateWorkoutPlan' : ActorMethod<[bigint, WorkoutPlan], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];