/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MealTemplate = IDL.Record({
  'allergy_tags' : IDL.Vec(IDL.Text),
  'calories' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'protein_g' : IDL.Float64,
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'carbs_g' : IDL.Float64,
  'fat_g' : IDL.Float64,
});
export const WorkoutExercise = IDL.Record({
  'duration_seconds' : IDL.Nat,
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'animation_type' : IDL.Text,
  'muscle_group' : IDL.Text,
});
export const WorkoutPlan = IDL.Record({
  'duration_minutes' : IDL.Nat,
  'goal' : IDL.Text,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(WorkoutExercise),
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MacroTargets = IDL.Record({
  'protein_g' : IDL.Float64,
  'carbs_g' : IDL.Float64,
  'fat_g' : IDL.Float64,
});
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'weight_kg' : IDL.Float64,
  'daily_calories' : IDL.Nat,
  'goal' : IDL.Text,
  'name' : IDL.Text,
  'macro_targets' : MacroTargets,
  'last_active' : Timestamp,
  'dietary_restrictions' : IDL.Vec(IDL.Text),
  'height_cm' : IDL.Float64,
});
export const FoodLogEntry = IDL.Record({
  'date' : IDL.Text,
  'calories' : IDL.Float64,
  'meal_type' : IDL.Text,
  'protein_g' : IDL.Float64,
  'carbs_g' : IDL.Float64,
  'food_name' : IDL.Text,
  'fat_g' : IDL.Float64,
});
export const DailyTotals = IDL.Record({
  'calories' : IDL.Float64,
  'protein_g' : IDL.Float64,
  'carbs_g' : IDL.Float64,
  'fat_g' : IDL.Float64,
});
export const DailyFoodSummary = IDL.Record({
  'entries' : IDL.Vec(FoodLogEntry),
  'totals' : DailyTotals,
});
export const WeightEntry = IDL.Record({
  'weight_kg' : IDL.Float64,
  'date' : IDL.Text,
});
export const WorkoutLog = IDL.Record({
  'duration_minutes' : IDL.Nat,
  'date' : IDL.Text,
  'workout_plan_id' : IDL.Nat,
  'completed' : IDL.Bool,
  'calories_burned' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMealTemplate' : IDL.Func([MealTemplate], [IDL.Nat], []),
  'addWorkoutPlan' : IDL.Func([WorkoutPlan], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateBMI' : IDL.Func([], [IDL.Float64], ['query']),
  'chatWithNutritionAI' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteMealTemplate' : IDL.Func([IDL.Nat], [], []),
  'filterMealsByDietaryRestrictions' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(MealTemplate)],
      ['query'],
    ),
  'getAIMealSuggestions' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Text],
      [],
    ),
  'getAIWorkoutRecommendation' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllMealTemplates' : IDL.Func([], [IDL.Vec(MealTemplate)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMealLogsByDate' : IDL.Func([IDL.Text], [DailyFoodSummary], ['query']),
  'getMealTemplate' : IDL.Func([IDL.Nat], [MealTemplate], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeightHistory' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
  'getWorkoutPlan' : IDL.Func([IDL.Nat], [WorkoutPlan], ['query']),
  'getWorkoutsByDate' : IDL.Func([IDL.Text], [IDL.Vec(WorkoutLog)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logMeal' : IDL.Func([FoodLogEntry], [], []),
  'logWeight' : IDL.Func([WeightEntry], [], []),
  'logWorkout' : IDL.Func([WorkoutLog], [], []),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMealTemplate' : IDL.Func([IDL.Nat, MealTemplate], [], []),
  'updateUser' : IDL.Func([UserProfile], [], []),
  'updateWorkoutPlan' : IDL.Func([IDL.Nat, WorkoutPlan], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MealTemplate = IDL.Record({
    'allergy_tags' : IDL.Vec(IDL.Text),
    'calories' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'protein_g' : IDL.Float64,
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'carbs_g' : IDL.Float64,
    'fat_g' : IDL.Float64,
  });
  const WorkoutExercise = IDL.Record({
    'duration_seconds' : IDL.Nat,
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'animation_type' : IDL.Text,
    'muscle_group' : IDL.Text,
  });
  const WorkoutPlan = IDL.Record({
    'duration_minutes' : IDL.Nat,
    'goal' : IDL.Text,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(WorkoutExercise),
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MacroTargets = IDL.Record({
    'protein_g' : IDL.Float64,
    'carbs_g' : IDL.Float64,
    'fat_g' : IDL.Float64,
  });
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'weight_kg' : IDL.Float64,
    'daily_calories' : IDL.Nat,
    'goal' : IDL.Text,
    'name' : IDL.Text,
    'macro_targets' : MacroTargets,
    'last_active' : Timestamp,
    'dietary_restrictions' : IDL.Vec(IDL.Text),
    'height_cm' : IDL.Float64,
  });
  const FoodLogEntry = IDL.Record({
    'date' : IDL.Text,
    'calories' : IDL.Float64,
    'meal_type' : IDL.Text,
    'protein_g' : IDL.Float64,
    'carbs_g' : IDL.Float64,
    'food_name' : IDL.Text,
    'fat_g' : IDL.Float64,
  });
  const DailyTotals = IDL.Record({
    'calories' : IDL.Float64,
    'protein_g' : IDL.Float64,
    'carbs_g' : IDL.Float64,
    'fat_g' : IDL.Float64,
  });
  const DailyFoodSummary = IDL.Record({
    'entries' : IDL.Vec(FoodLogEntry),
    'totals' : DailyTotals,
  });
  const WeightEntry = IDL.Record({
    'weight_kg' : IDL.Float64,
    'date' : IDL.Text,
  });
  const WorkoutLog = IDL.Record({
    'duration_minutes' : IDL.Nat,
    'date' : IDL.Text,
    'workout_plan_id' : IDL.Nat,
    'completed' : IDL.Bool,
    'calories_burned' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMealTemplate' : IDL.Func([MealTemplate], [IDL.Nat], []),
    'addWorkoutPlan' : IDL.Func([WorkoutPlan], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateBMI' : IDL.Func([], [IDL.Float64], ['query']),
    'chatWithNutritionAI' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteMealTemplate' : IDL.Func([IDL.Nat], [], []),
    'filterMealsByDietaryRestrictions' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(MealTemplate)],
        ['query'],
      ),
    'getAIMealSuggestions' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Text],
        [],
      ),
    'getAIWorkoutRecommendation' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllMealTemplates' : IDL.Func([], [IDL.Vec(MealTemplate)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMealLogsByDate' : IDL.Func([IDL.Text], [DailyFoodSummary], ['query']),
    'getMealTemplate' : IDL.Func([IDL.Nat], [MealTemplate], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeightHistory' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
    'getWorkoutPlan' : IDL.Func([IDL.Nat], [WorkoutPlan], ['query']),
    'getWorkoutsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkoutLog)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logMeal' : IDL.Func([FoodLogEntry], [], []),
    'logWeight' : IDL.Func([WeightEntry], [], []),
    'logWorkout' : IDL.Func([WorkoutLog], [], []),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMealTemplate' : IDL.Func([IDL.Nat, MealTemplate], [], []),
    'updateUser' : IDL.Func([UserProfile], [], []),
    'updateWorkoutPlan' : IDL.Func([IDL.Nat, WorkoutPlan], [], []),
  });
};

export const init = ({ IDL }) => { return []; };